dataset:
  name: cifar10
  root: "./data"
  num_workers: 2
  img_height: 32
  img_width: 32
  in_channels: 3
  num_classes: 10
  transform: augment
  shuffle: 1

criterion:
  name: ce

soft_criterion:
  name: mixed_kl

optimizer:
  name: radam
  lr: 0.002
  weight_decay: 0.0005

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 200
  batch_size: 128
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 200
  train_noise: 0

mlg:
  projection_alg: null
  kd: False
  base_in: 0
  base_out: 0
  basis_bit: 32
  coeff_in_bit: 32
  coeff_out_bit: 32

checkpoint:
  save_best_model_k: 1
  checkpoint_dir: "default"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

quantize:
  quant_ratio_basis: 1
  quant_ratio_coeff_in: 1
  quant_ratio_coeff_out: 1
  quant_ratio_in: 1

model:
  name: "ResNet18"
  weight_bit: 32
  input_bit: 32

teacher:
  name: "ResNet18"
  checkpoint: ""
  weight_bit: 32
  input_bit: 32

debug:
  verbose: 1

