criterion:
  name: ce

optimizer:
  name: radam
  lr: 0.002
  weight_decay: 0.0005

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "cifar10_resnet18_pretrain"
  n_epochs: 200
  batch_size: 128

mlg:
  projection_alg: null
  kd: False
  base_in: 0
  base_out: 0
  basis_bit: 32
  coeff_in_bit: 32
  coeff_out_bit: 32

quantize:
  quant_ratio_basis: 1
  quant_ratio_coeff_in: 1
  quant_ratio_coeff_out: 1
  quant_ratio_in: 1

checkpoint:
  save_best_model_k: 1
  checkpoint_dir: "cifar10/resnet18/pretrain"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  teacher_checkpoint: ""
  no_linear: 0

model:
  name: "ResNet18"
  weight_bit: 15
  input_bit: 32

teacher:
  name: "ResNet18"
  checkpoint: ""
  weight_bit: 15
  input_bit: 32

debug:
  verbose: 1

